version: '{build}'
image: Visual Studio 2022
nuget:
  disable_publish_octopus: true
build_script:
 - dotnet test
 - dotnet build --configuration Release
 - dotnet pack --no-build src/Overcrowdin/Overcrowdin.csproj
artifacts:
- path: '**/*nupkg'
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
  on:
    branch: master
