version: '{build}'
image: Visual Studio 2017
nuget:
  disable_publish_octopus: true
before_build:
- cmd: >-
    git submodule update --init

    nuget restore
build:
  project: Overcrowdin.sln
  verbosity: minimal
after_build:
- cmd: dotnet pack --no-build src/Overcrowdin/Overcrowdin.csproj
artifacts:
- path: '**/*nupkg'
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
  on:
    branch: master
