//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvercrowdinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OvercrowdinTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;info&gt;\\n
        ///  &lt;languages&gt;\\n
        ///    &lt;item&gt;\\n
        ///      &lt;name&gt;Acholi&lt;/name&gt;\\n
        ///      &lt;code&gt;ach&lt;/code&gt;\\n
        ///      &lt;can_translate&gt;1&lt;/can_translate&gt;\\n
        ///      &lt;can_approve&gt;1&lt;/can_approve&gt;\\n
        ///    &lt;/item&gt;\\n
        ///  &lt;/languages&gt;\\n
        ///  &lt;files/&gt;\\n
        ///  &lt;details&gt;\\n
        ///    &lt;source_language&gt;\\n
        ///      &lt;name&gt;English&lt;/name&gt;\\n
        ///      &lt;code&gt;en&lt;/code&gt;\\n
        ///    &lt;/source_language&gt;\\n
        ///    &lt;name&gt;CrowdinApiTestProject&lt;/name&gt;\\n
        ///    &lt;identifier&gt;crowdinapitestproject&lt;/identifier&gt;\\n
        ///    &lt;created&gt;20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrowdinProjInfoResponseNoFiles {
            get {
                return ResourceManager.GetString("CrowdinProjInfoResponseNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;info&gt;\\n
        ///  &lt;languages&gt;\\n
        ///    &lt;item&gt;\\n
        ///      &lt;name&gt;Acholi&lt;/name&gt;\\n
        ///      &lt;code&gt;ach&lt;/code&gt;\\n
        ///      &lt;can_translate&gt;1&lt;/can_translate&gt;\\n
        ///      &lt;can_approve&gt;1&lt;/can_approve&gt;\\n
        ///    &lt;/item&gt;\\n
        ///  &lt;/languages&gt;\\n
        ///  &lt;files&gt;\\n
        ///    &lt;item&gt;\\n
        ///      &lt;node_type&gt;file&lt;/node_type&gt;\\n
        ///      &lt;id&gt;4&lt;/id&gt;\\n
        ///      &lt;name&gt;test.json&lt;/name&gt;\\n
        ///      &lt;created&gt;2019-11-14T22:02:27+0000&lt;/created&gt;\\n
        ///      &lt;last_updated&gt;2019-11-15T21:46:36+0000&lt;/last_updated&gt;\\n
        ///      &lt;last_acc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrowdinProjInfoResponseWithFiles {
            get {
                return ResourceManager.GetString("CrowdinProjInfoResponseWithFiles", resourceCulture);
            }
        }
    }
}
